# グローバル設定
expiration_days: 3  # 履歴を削除する日数
max_entries: 10  # 投稿する記事の上限

# 各ジャンルの設定
genres:
  ゲーム:
    rss_feeds:
      - "https://www.4gamer.net/rss/news_topics.xml"
      - "https://www.nhk.or.jp/rss/news/cat0.xml"
  テクノロジー:
    rss_feeds:
      - "https://www.txhd.co.jp/rss.xml"
