name: Post RSS to Discord

on:
  workflow_dispatch:  # 手動実行
  schedule:
    - cron: "0 22 * * *"  # JST 7:00 → UTC 22:00 (前日)
    - cron: "0 4 * * *"   # JST 13:00 → UTC 4:00
    - cron: "0 10 * * *"  # JST 19:00 → UTC 10:00

permissions:
  contents: write

jobs:
  post_news:
    runs-on: ubuntu-latest
    steps:
      # -------------------------
      # 1) リポジトリをチェックアウト
      # -------------------------
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # -------------------------
      # 2) Python セットアップ
      # -------------------------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # -------------------------
      # 3) キャッシュの設定
      #    requirements.txt に変更がなければ、前回のキャッシュを復元
      # -------------------------
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # -------------------------
      # 4) 依存パッケージのインストール
      # -------------------------
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # -------------------------
      # 5) Python スクリプトを実行
      #    成功 (exit 0) なら success()
      #    失敗 (exit != 0) なら failure()
      # -------------------------
      - name: Run Python script
        id: python_script
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
          FORUM_CHANNEL_ID: ${{ secrets.FORUM_CHANNEL_ID }}
        run: |
          python -m scripts.post_news

      # -------------------------
      # 6) 成功時のみ posted_links.yaml をコミット＆プッシュ
      # -------------------------
      - name: Commit and push updated posted_links.yaml
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add datas/posted_links.yaml
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update posted_links.yaml"
            git push origin ${{ github.ref }}
          fi

      # -------------------------
      # 7) 失敗時は Discord に通知
      # -------------------------
      - name: Notify Discord on failure
        if: failure()
        env:
          POST_ERROR_NOTIFICATION: ${{ secrets.POST_ERROR_NOTIFICATION }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{
                \"content\": \"**GitHub Actions Error**: RSS to Discord 投稿中にエラーが発生しました。\\n\\n\
                **ジョブ番号**: #${{ github.run_number }}\\n\
                **ジョブURL**: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"
              }" \
          "$POST_ERROR_NOTIFICATION"
