name: Post RSS to Discord

on:
  schedule:
    - cron: "0 * * * *"  # 毎時0分に実行
  workflow_dispatch:  # 手動実行を有効にする

jobs:
  post_news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if artifact exists
        id: check_artifact
        run: |
          if curl -s --head --fail --location "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | grep '"name":"posted-links"'; then
            echo "artifact_exists=true" >> $GITHUB_ENV
          else
            echo "artifact_exists=false" >> $GITHUB_ENV
          fi

      - name: Restore posted links if artifact exists
        if: env.artifact_exists == 'true'
        uses: actions/download-artifact@v3
        with:
          name: posted-links
          path: .

      - name: Ensure posted_links.json exists
        run: |
          if [ ! -f posted_links.json ]; then
            echo "[]" > posted_links.json
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install feedparser requests

      - name: Run Python script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python post_news.py

      - name: Save posted links
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: posted-links
          path: posted_links.json
