name: Post RSS to Discord

on:
  workflow_dispatch:  # 手動実行を有効にする

permissions:
  contents: write  # リポジトリへの書き込み権限

jobs:
  post_news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install feedparser requests pyyaml

      # ---- Python スクリプト実行 ----
      - name: Run Python script
        id: python_script  # このIDでoutputsを参照できる
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
          FORUM_CHANNEL_ID: ${{ secrets.FORUM_CHANNEL_ID }}
        run: |
          python post_news.py

      # ---- 成功時のみ posted_links.yaml をコミット＆プッシュ ----
      - name: Commit and push updated posted_links.yaml
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add posted_links.yaml
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update posted_links.yaml"
            git push origin ${{ github.ref }}
          fi

      # ---- 失敗時のみ、Discordに通知 ----
      - name: Notify Discord on failure
        if: failure()
        env:
          POST_ERROR_NOTIFICATION: ${{ secrets.POST_ERROR_NOTIFICATION }}
        run: |
          echo "=== GitHub Actions failure notification ==="

          # 1) Pythonスクリプトがset_github_action_error_message()で書き込んだ出力を取得
          RAW_MSG="${{ steps.python_script.outputs.error_message }}"

          # 2) sedでJSON用にエスケープ
          #    - ダブルクォート (") → \" に変換
          #    - 改行 (\n) → \\n に変換
          ESCAPED_MSG=$(echo "$RAW_MSG" \
            | sed 's/"/\\"/g' \
            | sed ':a;N;$!ba;s/\n/\\n/g')

          # 必要に応じて { や } をエスケープしたい場合は、さらに
          # sed 's/{/\\{/g' などを追加

          # 3) curlでDiscordに送信
          #    contentに直接$ESCAPED_MSGを組み込む
          curl -X POST -H "Content-Type: application/json" \
          -d "{
                \"content\": \"**GitHub Actions Error**: RSS to Discord 投稿中にエラーが発生しました。\\n\\n\
                **ジョブ番号**: #${{ github.run_number }}\\n\
                **ジョブURL**: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\\n\\n\
                **エラーメッセージ**: $ESCAPED_MSG\"
              }" \
          "$POST_ERROR_NOTIFICATION"
